version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app:ro
      - data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: >
      sh -c "
        echo 'Current directory:' &&
        pwd &&
        echo 'Files in current directory:' &&
        ls -la &&
        echo 'Starting server...' &&
        uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
      "

volumes:
  data:
    driver: local
  redis_data:
    driver: local